export const provinces = [
    { PROVINCE_ID: 1, PROVINCE_NAME: "Thailand" },
    { PROVINCE_ID: 2, PROVINCE_NAME: "Japan" },
    { PROVINCE_ID: 3, PROVINCE_NAME: "South Korea" },
    { PROVINCE_ID: 4, PROVINCE_NAME: "United States" },
    { PROVINCE_ID: 5, PROVINCE_NAME: "Mexico" },
    { PROVINCE_ID: 6, PROVINCE_NAME: "Brazil" },
    { PROVINCE_ID: 7, PROVINCE_NAME: "France" },
    { PROVINCE_ID: 8, PROVINCE_NAME: "Italy" },
    { PROVINCE_ID: 9, PROVINCE_NAME: "Germany" },
    { PROVINCE_ID: 10, PROVINCE_NAME: "India" },
    { PROVINCE_ID: 11, PROVINCE_NAME: "Vietnam" },
    { PROVINCE_ID: 12, PROVINCE_NAME: "China" },
    { PROVINCE_ID: 13, PROVINCE_NAME: "Australia" },
    { PROVINCE_ID: 14, PROVINCE_NAME: "Canada" },
    { PROVINCE_ID: 15, PROVINCE_NAME: "United Kingdom" },
    { PROVINCE_ID: 16, PROVINCE_NAME: "Spain" },
    { PROVINCE_ID: 17, PROVINCE_NAME: "Netherlands" },
    { PROVINCE_ID: 18, PROVINCE_NAME: "Russia" },
    { PROVINCE_ID: 19, PROVINCE_NAME: "Argentina" },
    { PROVINCE_ID: 20, PROVINCE_NAME: "South Africa" },
    { PROVINCE_ID: 21, PROVINCE_NAME: "New Zealand" },
    { PROVINCE_ID: 22, PROVINCE_NAME: "Singapore" },
    { PROVINCE_ID: 23, PROVINCE_NAME: "Malaysia" },
    { PROVINCE_ID: 24, PROVINCE_NAME: "Indonesia" },
    { PROVINCE_ID: 25, PROVINCE_NAME: "Philippines" },
    { PROVINCE_ID: 26, PROVINCE_NAME: "Turkey" },
    { PROVINCE_ID: 27, PROVINCE_NAME: "Egypt" },
    { PROVINCE_ID: 28, PROVINCE_NAME: "United Arab Emirates" },
    { PROVINCE_ID: 29, PROVINCE_NAME: "Pakistan" },
    { PROVINCE_ID: 30, PROVINCE_NAME: "Bangladesh" },
    { PROVINCE_ID: 31, PROVINCE_NAME: "Nigeria" },
    { PROVINCE_ID: 32, PROVINCE_NAME: "Kenya" },
    { PROVINCE_ID: 33, PROVINCE_NAME: "Somalia" },
    { PROVINCE_ID: 34, PROVINCE_NAME: "Sweden" },
    { PROVINCE_ID: 35, PROVINCE_NAME: "Belgium" },
    { PROVINCE_ID: 36, PROVINCE_NAME: "Poland" },
    { PROVINCE_ID: 37, PROVINCE_NAME: "Switzerland" },
    { PROVINCE_ID: 38, PROVINCE_NAME: "Greece" },
    { PROVINCE_ID: 39, PROVINCE_NAME: "Portugal" },
    { PROVINCE_ID: 40, PROVINCE_NAME: "Finland" },
    { PROVINCE_ID: 41, PROVINCE_NAME: "Denmark" },
    { PROVINCE_ID: 42, PROVINCE_NAME: "Norway" },
    { PROVINCE_ID: 43, PROVINCE_NAME: "Iceland" },
    { PROVINCE_ID: 44, PROVINCE_NAME: "Ireland" },
    { PROVINCE_ID: 45, PROVINCE_NAME: "Czech Republic" },
    { PROVINCE_ID: 46, PROVINCE_NAME: "Hungary" },
    { PROVINCE_ID: 47, PROVINCE_NAME: "Romania" },
    { PROVINCE_ID: 48, PROVINCE_NAME: "Slovakia" },
    { PROVINCE_ID: 49, PROVINCE_NAME: "Bulgaria" },
    { PROVINCE_ID: 50, PROVINCE_NAME: "Serbia" },
    { PROVINCE_ID: 51, PROVINCE_NAME: "Croatia" },
    { PROVINCE_ID: 52, PROVINCE_NAME: "Slovenia" },
    { PROVINCE_ID: 53, PROVINCE_NAME: "Bosnia and Herzegovina" },
    { PROVINCE_ID: 54, PROVINCE_NAME: "North Macedonia" },
    { PROVINCE_ID: 55, PROVINCE_NAME: "Montenegro" },
    { PROVINCE_ID: 56, PROVINCE_NAME: "Albania" },
    { PROVINCE_ID: 57, PROVINCE_NAME: "Kosovo" },
    { PROVINCE_ID: 58, PROVINCE_NAME: "Georgia" },
    { PROVINCE_ID: 59, PROVINCE_NAME: "Armenia" },
    { PROVINCE_ID: 60, PROVINCE_NAME: "Azerbaijan" },
    { PROVINCE_ID: 61, PROVINCE_NAME: "Kuwait" },
    { PROVINCE_ID: 62, PROVINCE_NAME: "Jordan" },
    { PROVINCE_ID: 63, PROVINCE_NAME: "Monaco" },
    { PROVINCE_ID: 64, PROVINCE_NAME: "Israel" },
    { PROVINCE_ID: 65, PROVINCE_NAME: "Syria" },
    { PROVINCE_ID: 66, PROVINCE_NAME: "Lebanon" },
    { PROVINCE_ID: 67, PROVINCE_NAME: "Cyprus" },
    { PROVINCE_ID: 68, PROVINCE_NAME: "Qatar" },
    { PROVINCE_ID: 69, PROVINCE_NAME: "Oman" },
    { PROVINCE_ID: 70, PROVINCE_NAME: "Afghanistan" },
    { PROVINCE_ID: 71, PROVINCE_NAME: "Kazakhstan" },
    { PROVINCE_ID: 72, PROVINCE_NAME: "Uzbekistan" },
    { PROVINCE_ID: 73, PROVINCE_NAME: "Turkmenistan" },
    { PROVINCE_ID: 74, PROVINCE_NAME: "Kyrgyzstan" },
    { PROVINCE_ID: 75, PROVINCE_NAME: "Tajikistan" },
    { PROVINCE_ID: 76, PROVINCE_NAME: "Mongolia" },
    { PROVINCE_ID: 77, PROVINCE_NAME: "Bhutan" },
    { PROVINCE_ID: 78, PROVINCE_NAME: "!Unknow" },
  ];
  